### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Devendra-Kumar-Dhayal** [hoangxq/auto-complete-udemy-course#1]

**Comment by hoangxq** [comment]
Can you describe the problem specifically. I checked and it still works.

**Comment by hoangxq** [comment]
I apologize for my mistake.
I fixed it in the script and updated the new version on the extension.
The new version will be published soon. Please wait for the update notification of the new version (2.1) and it will work

**Comment by hoangxq** [comment]
New version has been released. Please check.
